[package]
name = "upd_exchange"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
threadpool = "1.0"
exchange_protocol = { path = "../exchange_protocol" }