[package]
name = "tcp_exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.20.1", features = ["full"] }
exchange_protocol = { path = "../exchange_protocol" }